class DietTable {
  final String id;
  final List<String> allowedUz;
  final List<String> forbiddenUz;
  final List<String> allowedRu;
  final List<String> forbiddenRu;
  final String descriptionUz;
  final String descriptionRu;

  const DietTable({
    required this.id,
    required this.allowedUz,
    required this.forbiddenUz,
    required this.allowedRu,
    required this.forbiddenRu,
    required this.descriptionUz,
    required this.descriptionRu,
  });
}

class DietConstants {
  static const List<String> diseaseOptions = [
    'Surunkali virusli B gepatiti',
    'Surunkali virusli C gepatiti',
    'Autoimmun gepatit',
    'Jigar yogli gepatozi',
    'Alkogolli jigar kasalligi',
    'Toksik gepatit',
    'Jigar sirrozi',
    'Jigar fibrozi',
    'Jigar yetishmovchiligi',
    'Xolangit',
    'Xolesistit',
    'Jigar exinokokkozi',
    'Surunkali gastrit',
    'Oshqozon yara kasalligi',
    'On ikki barmoq ichak yarasi',
    'Gastroduodenit',
    'Reflyuks ezofagit',
    'Enterit',
    'Kolit',
    'Enterokolit',
    'Kron kasalligi',
    'Pankreatit',
    'Ot-tosh kasalligi',
    'Qabziyat',
    'Diareya',
    'Ichak qozgaluvchanlik sindromi',
    '1-tip qandli diabet',
    '2-tip qandli diabet',
    'Semirish',
    'Metabolik sindrom',
    'Gipotireoz',
    'Gipertireoz',
    'Tireotoksikoz',
    'Autoimmun tireoidit',
    'Qandsiz diabet',
    'Icenko-Kushing sindromi',
    'Addison kasalligi',
    'Podagra',
    'Diabetik nefropatiya',
    'Insulinorezistentlik',
    'Arterial gipertenziya',
    'Gipertonik kasallik',
    'Ishemik yurak kasalligi',
    'Stenokardiya',
    'Miokard infarkti',
    'Yurak yetishmovchiligi',
    'Aritmiya',
    'Taxikardiya',
    'Bradikardiya',
    'Ateroskleroz',
    'Kardiomiopatiya',
    'Miokardit',
    'Endokardit',
    'Perikardit',
    'Varikoz kasalligi',
    'Tromboflebit',
    'Yurak nuqsonlari',
    'Giperlipidemiya',
    'Insultdan keyingi holat',
  ];

  static const Map<String, String> diseaseToTable = {
    'Surunkali virusli B gepatiti': '№5',
    'Surunkali virusli C gepatiti': '№5',
    'Autoimmun gepatit': '№5',
    'Jigar yogli gepatozi': '№5',
    'Alkogolli jigar kasalligi': '№5',
    'Toksik gepatit': '№5',
    'Jigar sirrozi': '№5',
    'Jigar fibrozi': '№5',
    'Jigar yetishmovchiligi': '№5a',
    'Xolangit': '№5',
    'Xolesistit': '№5',
    'Jigar exinokokkozi': '№5',
    'Surunkali gastrit': '№1',
    'Oshqozon yara kasalligi': '№1',
    'On ikki barmoq ichak yarasi': '№1',
    'Gastroduodenit': '№1',
    'Reflyuks ezofagit': '№1',
    'Enterit': '№4',
    'Kolit': '№4',
    'Enterokolit': '№4',
    'Kron kasalligi': '№4',
    'Pankreatit': '№5p',
    'Ot-tosh kasalligi': '№5',
    'Qabziyat': '№3',
    'Diareya': '№4',
    'Ichak qozgaluvchanlik sindromi': '№3',
    '1-tip qandli diabet': '№9',
    '2-tip qandli diabet': '№9',
    'Semirish': '№8',
    'Metabolik sindrom': '№8',
    'Gipotireoz': '№8',
    'Gipertireoz': '№15',
    'Tireotoksikoz': '№15',
    'Autoimmun tireoidit': '№15',
    'Qandsiz diabet': '№15',
    'Icenko-Kushing sindromi': '№8',
    'Addison kasalligi': '№15',
    'Podagra': '№6',
    'Diabetik nefropatiya': '№7',
    'Insulinorezistentlik': '№9',
    'Arterial gipertenziya': '№10',
    'Gipertonik kasallik': '№10',
    'Ishemik yurak kasalligi': '№10',
    'Stenokardiya': '№10',
    'Miokard infarkti': '№10i',
    'Yurak yetishmovchiligi': '№10',
    'Aritmiya': '№10',
    'Taxikardiya': '№10',
    'Bradikardiya': '№10',
    'Ateroskleroz': '№10s',
    'Kardiomiopatiya': '№10',
    'Miokardit': '№10',
    'Endokardit': '№10',
    'Perikardit': '№10',
    'Varikoz kasalligi': '№10',
    'Tromboflebit': '№10',
    'Yurak nuqsonlari': '№10',
    'Giperlipidemiya': '№10s',
    'Insultdan keyingi holat': '№10',
  };

  static const Map<String, String> _legacyCyrillicDiseaseNames = {
    'Сурункали гастрит': 'Surunkali gastrit',
    'Ошқозон яра касаллиги': 'Oshqozon yara kasalligi',
    'Ўн икки бармоқ ичак яраси': 'On ikki barmoq ichak yarasi',
    'Қабзият': 'Qabziyat',
    'Диарея': 'Diareya',
    'Семириш': 'Semirish',
    'Артериал гипертензия': 'Arterial gipertenziya',
    'Гипертоник касаллик': 'Gipertonik kasallik',
    'Ишемик юрак касаллиги': 'Ishemik yurak kasalligi',
    'Юрак етишмовчилиги': 'Yurak yetishmovchiligi',
  };

  static String normalizeDiseaseName(String disease) {
    return _legacyCyrillicDiseaseNames[disease] ?? disease;
  }

  static String getTableId(String disease) {
    final normalized = normalizeDiseaseName(disease);
    return diseaseToTable[normalized] ?? '№15';
  }

  static const Map<String, DietTable> dietTables = {
    '№1': DietTable(
      id: '№1',
      descriptionUz: 'Oshqozon va ichak yara kasalliklarida tavsiya etiladi.',
      descriptionRu: 'Рекомендуется при язвенной болезни желудка и кишечника.',
      allowedUz: [
        'Suyuq shorvalar',
        'Botqalar',
        'Bugda pishgan kotlet',
        'Pyure',
        'Omlet',
      ],
      forbiddenUz: [
        'Qovurilgan ovqat',
        'Achchiq taom',
        'Gazli ichimlik',
        'Kofe',
        'Moyli gosht',
      ],
      allowedRu: ['Слизистые супы', 'Каши', 'Паровые котлеты', 'Пюре', 'Омлет'],
      forbiddenRu: ['Жареное', 'Острое', 'Газировка', 'Кофе', 'Жирное мясо'],
    ),
    '№3': DietTable(
      id: '№3',
      descriptionUz: 'Qabziyatda kletchatkaga boy ovqatlar tavsiya qilinadi.',
      descriptionRu: 'При запорах рекомендуется пища, богатая клетчаткой.',
      allowedUz: ['Sabzavotlar', 'Meva', 'Qora non', 'Kefir'],
      forbiddenUz: ['Oq non', 'Guruchli botqa', 'Qattiq choy'],
      allowedRu: ['Овощи', 'Фрукты', 'Черный хлеб', 'Кефир'],
      forbiddenRu: ['Белый хлеб', 'Рисовая каша', 'Крепкий чай'],
    ),
    '№4': DietTable(
      id: '№4',
      descriptionUz:
          'Ichak kasalliklari va diareyada yengil hazm boladigan ovqat.',
      descriptionRu: 'Легкоусвояемая пища при заболеваниях кишечника и диарее.',
      allowedUz: ['Guruchli suv', 'Qotirilgan non', 'Yogsiz gosht buloni'],
      forbiddenUz: ['Sut', 'Yangi mevalar', 'Dukkaklilar'],
      allowedRu: ['Рисовый отвар', 'Сухари', 'Нежирный мясной бульон'],
      forbiddenRu: ['Молоко', 'Свежие фрукты', 'Бобовые'],
    ),
    '№5': DietTable(
      id: '№5',
      descriptionUz: 'Jigar va ot yollarida muammo bolganda tavsiya etiladi.',
      descriptionRu: 'При заболеваниях печени и желчевыводящих путей.',
      allowedUz: [
        'Yogsiz gosht',
        'Baliq',
        'Sabzavotlar',
        'Botqalar',
        'Sut mahsulotlari',
      ],
      forbiddenUz: [
        'Yogli ovqat',
        'Alkogol',
        'Dudlangan mahsulotlar',
        'Mayonez',
        'Tuxum sarigi',
      ],
      allowedRu: [
        'Нежирное мясо',
        'Рыба',
        'Овощи',
        'Каши',
        'Молочные продукты',
      ],
      forbiddenRu: ['Жирное', 'Алкоголь', 'Копчёности', 'Майонез', 'Желток'],
    ),
    '№8': DietTable(
      id: '№8',
      descriptionUz: 'Semirishda kaloriya cheklangan parhez.',
      descriptionRu: 'Низкокалорийная диета при ожирении.',
      allowedUz: ['Sabzavotlar', 'Kefir', 'Olma', 'Yogsiz gosht'],
      forbiddenUz: ['Fastfud', 'Shirinliklar', 'Gazli ichimlik', 'Shakar'],
      allowedRu: ['Овощи', 'Кефир', 'Яблоки', 'Нежирное мясо'],
      forbiddenRu: ['Фастфуд', 'Сладости', 'Газировка', 'Сахар'],
    ),
    '№9': DietTable(
      id: '№9',
      descriptionUz: 'Qandli diabet uchun uglevod nazorati.',
      descriptionRu: 'Контроль углеводов при сахарном диабете.',
      allowedUz: ['Sabzavotlar', 'Grechka', 'Yogsiz gosht', 'Qora non'],
      forbiddenUz: ['Shakar', 'Tort', 'Konfet', 'Shirin ichimliklar', 'Oq non'],
      allowedRu: ['Овощи', 'Гречка', 'Нежирное мясо', 'Чёрный хлеб'],
      forbiddenRu: [
        'Сахар',
        'Торты',
        'Конфеты',
        'Сладкие напитки',
        'Белый хлеб',
      ],
    ),
    '№10': DietTable(
      id: '№10',
      descriptionUz: 'Yurak-qon tomir kasalliklarida tavsiya etiladi.',
      descriptionRu: 'При сердечно-сосудистых заболеваниях.',
      allowedUz: ['Sabzavotlar', 'Baliq', 'Banan', 'Grechka'],
      forbiddenUz: ['Tuz', 'Qovurilgan ovqat', 'Alkogol', 'Qattiq kofe'],
      allowedRu: ['Овощи', 'Рыба', 'Банан', 'Гречка'],
      forbiddenRu: ['Соль', 'Жареное', 'Алкоголь', 'Крепкий кофе'],
    ),
    '№15': DietTable(
      id: '№15',
      descriptionUz: 'Umumiy soglom ovqatlanish stoli.',
      descriptionRu: 'Общий стол здорового питания.',
      allowedUz: ['Barcha soglom taomlar'],
      forbiddenUz: ['Haddan tashqari yogli va shirin taomlar'],
      allowedRu: ['Все здоровые продукты'],
      forbiddenRu: ['Чрезмерно жирная и сладкая пища'],
    ),
  };
}
